import { describe, expect, it } from "vitest";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { SUPPORTED_LOCALES, matchLocale } from "../index";
import barrel from "../translations.barrel.json";

/**
 * Poki localization rules LOC-02 (one file, centralized) and LOC-04 (phase
 * order: EFIGS + Turkish, then CJK, then pt-BR + Russian) plus LOC-05
 * (browser-language detection). A missing string in one locale is exactly the
 * kind of defect that only shows up on a device the developer does not own, so
 * it is a build failure here instead.
 */
const entries = Object.entries((barrel as { barrel: Record<string, { placeholders: string[]; translations: Record<string, string> }> }).barrel);

const PHASE_1 = ["en", "fr", "it", "de", "es", "tr"];
const PHASE_2_CJK = ["zh-CN", "ja", "ko"];
const PHASE_3 = ["pt-BR", "ru"];

describe("translation barrel (LOC-02)", () => {
  it("keeps every shipped locale complete", () => {
    const missing: string[] = [];
    for (const [key, entry] of entries) {
      for (const locale of SUPPORTED_LOCALES) {
        const value = entry.translations[locale.code];
        if (!value || !value.trim()) missing.push(`${locale.code}:${key}`);
      }
    }
    expect(missing).toEqual([]);
  });

  it("preserves every placeholder in every translation", () => {
    const broken: string[] = [];
    for (const [key, entry] of entries) {
      for (const [locale, value] of Object.entries(entry.translations)) {
        for (const token of entry.placeholders) {
          if (!value.includes(token)) broken.push(`${locale}:${key} missing ${token}`);
        }
      }
    }
    expect(broken).toEqual([]);
  });

  it("keeps the shipped barrel copies byte-identical (src ⇄ public ⇄ generated upload folder)", () => {
    const root = resolve(__dirname, "../../..");
    const read = (p: string) => readFileSync(resolve(root, p), "utf8");
    const src = read("src/i18n/translations.barrel.json");
    // public/ is the copy the runtime fetches; it must never drift.
    expect(read("public/i18n/translations.barrel.json")).toBe(src);
    // poki-upload/ is GENERATED by `pnpm build:poki` (it used to be a
    // hand-committed snapshot — which went stale and broke a real Inspector
    // upload). It is absent on a fresh clone; when a build has produced it, it
    // must match, and `scripts/verify-upload.mjs` proves that for the whole
    // folder including freshness against dist-poki/.
    const generated = resolve(root, "poki-upload/i18n/translations.barrel.json");
    if (existsSync(generated)) expect(readFileSync(generated, "utf8")).toBe(src);
  });
});

describe("locale coverage (LOC-04)", () => {
  it.each([...PHASE_1, ...PHASE_2_CJK, ...PHASE_3])("ships %s", (locale) => {
    expect(SUPPORTED_LOCALES.map((l) => l.code)).toContain(locale);
  });

  it("keeps the recommended phase order stable in the selector", () => {
    const codes = SUPPORTED_LOCALES.map((l) => l.code);
    const efigs = codes.indexOf("en");
    expect(codes.indexOf("tr")).toBeGreaterThan(efigs);
    expect(codes.indexOf("ru")).toBeGreaterThan(codes.indexOf("pt-BR") - 1);
  });
});

describe("browser-language detection (LOC-05)", () => {
  it("matches exact tags", () => {
    expect(matchLocale("de")).toBe("de");
    expect(matchLocale("tr-TR")).toBe("tr");
    expect(matchLocale("ru-RU")).toBe("ru");
  });

  it("falls back from a region variant to the same language", () => {
    expect(matchLocale("pt")).toBe("pt-BR");
    expect(matchLocale("pt-PT")).toBe("pt-BR");
    expect(matchLocale("zh-Hant")).toBe("zh-CN");
    expect(matchLocale("ja-JP")).toBe("ja");
  });

  it("is case- and separator-insensitive (BCP-47 spellings)", () => {
    expect(matchLocale("PT_br")).toBe("pt-BR");
    expect(matchLocale("  DE-at ")).toBe("de");
  });

  it("returns null for languages the game does not ship", () => {
    expect(matchLocale("fi-FI")).toBeNull();
    expect(matchLocale("")).toBeNull();
    expect(matchLocale(null)).toBeNull();
    expect(matchLocale(undefined)).toBeNull();
  });
});


describe("runtime packs (generated from the barrel)", () => {
  it("regenerates byte-identical packs from the barrel (no drift)", () => {
    const root = resolve(__dirname, "../../..");
    const barrel = JSON.parse(readFileSync(resolve(root, "src/i18n/translations.barrel.json"), "utf8")) as {
      barrel: Record<string, { translations: Record<string, string>; sourceText?: string }>;
    };
    const codes = [...new Set(Object.values(barrel.barrel).flatMap((e) => Object.keys(e.translations ?? {})))].sort();
    const drift: string[] = [];
    for (const code of codes) {
      const pack: Record<string, string> = {};
      for (const [key, entry] of Object.entries(barrel.barrel)) {
        const text = entry.translations[code] ?? entry.translations.en ?? entry.sourceText;
        if (typeof text === "string" && text.length > 0) pack[key] = text;
      }
      const ordered = Object.fromEntries(Object.entries(pack).sort(([a], [b]) => (a < b ? -1 : 1)));
      const expected = JSON.stringify(ordered, null, 1) + "\n";
      const actual = readFileSync(resolve(root, `src/i18n/packs/${code}.json`), "utf8");
      if (actual !== expected) drift.push(code);
    }
    expect(drift).toEqual([]);
  });

  it("every pack covers every key (fallback chain stays total)", () => {
    const root = resolve(__dirname, "../../..");
    const barrel = JSON.parse(readFileSync(resolve(root, "src/i18n/translations.barrel.json"), "utf8")) as {
      barrel: Record<string, unknown>;
    };
    const keys = Object.keys(barrel.barrel);
    for (const file of readdirSync(resolve(root, "src/i18n/packs"))) {
      const pack = JSON.parse(readFileSync(resolve(root, "src/i18n/packs", file), "utf8")) as Record<string, string>;
      const missing = keys.filter((k) => typeof pack[k] !== "string" || pack[k].length === 0);
      expect(missing, file).toEqual([]);
    }
  });
});
