export const PORTAL_DISPLAY_NAME = "Portal";
export const PORTAL_EDITION_NOTE = "Portal edition";
export const LEADERBOARD_CLOUD_LABEL = "☁️ cloud";
export const POKI_EDITION = false;
export const POKI_MULTIPLAYER = false;
export const SQUAD_CHAT = false;
export const CUSTOM_PILOT_NAMES = false;
export const SELL_AD_REMOVAL = false;
export const SIMULATED_BREAKS = false;
